### ISSUE TITLE
Fix Icon Drift

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-cards#1]
IMPORTANT Icons break - alignment gets slightly more offset each card, until it’s an entire line off by last cards. Must happen in the preflight fixing. Current best fix is to export as PDF in small groups to minimize offset. Print by template (split abilities by class, too big)

Filed as chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=586959

Longer term solution ideas:
Experiment with transforming the vertical cards a la horizontal cards, which don’t have drift
Generating PDF in Node: http://www.feedhenry.com/server-side-pdf-generation-node-js/
Workflow / macro that generates cards in tiny batches, then merge
Worst case, switch to Illustrator

**Comment by toddmedema** [comment]
Closing - no longer a visible / significant issue
